[package]
name = "vulkan_triangle"
version = "0.1.0"
edition = "2024"

[dependencies]
glfw = { version = "0.55", features = ["vulkan"] }
vk-sys = "0.5"
ash = "0.37"
ash-window = "0.12"
raw-window-handle = "0.5"
bytemuck = "1.14"
