[package]
name = "rust-vulkan-glfw-triangle"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
ash = "*"
nalgebra = "*"

[dependencies.glfw]
version = "*"
features = [ "vulkan" ]

[[bin]]
name = "rusteroids"
path = "src/main.rs"
