[package]
name = "obj_normalizer"
version = "0.1.0"
edition = "2021"

[workspace]
# Empty workspace to prevent inheriting from parent

[[bin]]
name = "obj_normalizer"
path = "obj_normalizer.rs"

[dependencies]
# No external dependencies - pure Rust stdlib
