//! Billboard renderer helper
//! 
//! Converts billboard quads into renderable geometry and coordinates
//! billboard rendering through the mesh pool system.

use super::{BillboardQuad, BillboardOrientation};
use super::orientation::*;
use crate::foundation::math::{Vec3, Mat4};
use crate::render::Camera;
use crate::render::systems::dynamic::{MeshPoolManager, MeshType};
use crate::render::resources::materials::{Material, UnlitMaterialParams};
use crate::render::api::RenderBackend;

/// Billboard renderer helper
pub struct BillboardRenderer;

impl BillboardRenderer {
    /// Convert a billboard quad to a transformation matrix
    pub fn calculate_billboard_matrix(
        billboard: &BillboardQuad,
        camera: &Camera,
    ) -> Mat4 {
        let camera_position = camera.position;
        let camera_up = camera.up;
        let billboard_position = billboard.position;
        let size = Vec3::new(billboard.size.x, billboard.size.y, 1.0);
        
        // Compute camera basis vectors directly from position and target
        let forward = (camera.target - camera_position).normalize();
        let right = forward.cross(&camera_up).normalize();
        let up = right.cross(&forward).normalize();
        
        match billboard.orientation {
            BillboardOrientation::ScreenAligned => {
                calculate_screen_aligned_matrix(
                    right,
                    up,
                    forward,
                    billboard_position,
                    size,
                )
            }
            BillboardOrientation::VelocityAligned { direction } => {
                calculate_velocity_aligned_matrix(
                    camera_position,
                    billboard_position,
                    direction,
                    size,
                )
            }
            BillboardOrientation::WorldAxisAligned { axis } => {
                calculate_world_axis_aligned_matrix(
                    camera_position,
                    billboard_position,
                    axis,
                    size,
                )
            }
        }
    }
}

/// Render billboard quads from the billboard mesh pool
///
/// Renders billboard quads generated by the trail system using instanced rendering
/// from the billboard mesh pool. Each billboard quad is rendered as an oriented
/// quad with velocity-aligned billboarding.
///
/// This is the primary interface between the trail/particle systems and the
/// rendering backend, analogous to how text rendering converts text layouts
/// into mesh pool allocations.
///
/// # Arguments
/// * `pool_manager` - Mutable reference to pool manager
/// * `_backend` - Backend renderer (unused, retained for API consistency)
/// * `billboard_quads` - Slice of billboard quads to render
/// * `camera` - Camera for billboard orientation calculations
///
/// # Returns
/// Result indicating successful billboard rendering
pub fn render_billboards_from_pool(
    pool_manager: &mut Option<MeshPoolManager>,
    _backend: &mut dyn RenderBackend,
    billboard_quads: &[BillboardQuad],
    camera: &Camera,
) -> Result<(), Box<dyn std::error::Error>> {
    if billboard_quads.is_empty() {
        return Ok(());
    }
    
    let mgr = pool_manager.as_mut()
        .ok_or("Pool manager not initialized")?;
    
    // Get the texture handle from the billboard pool (all billboards share this texture)
    let texture_handle = mgr.get_pool_texture(MeshType::Billboard)?;
    
    // Allocate and render each billboard as a dynamic object
    // This uses the existing pool system's instanced rendering
    let mut allocated_count = 0;
    for quad in billboard_quads {
        // Calculate billboard transformation matrix
        let transform = BillboardRenderer::calculate_billboard_matrix(quad, camera);
        
        // Billboards use the TransparentUnlit pipeline for proper alpha blending
        let mut material = Material::transparent_unlit(UnlitMaterialParams {
            color: Vec3::new(quad.color.x, quad.color.y, quad.color.z),
            alpha: quad.color.w,
        });
        
        // Attach the pool's texture so all billboards use the same texture
        if let Some(tex) = texture_handle {
            material = material.with_base_color_texture(tex);
        }
        
        // Allocate from billboard pool
        match mgr.allocate_instance(MeshType::Billboard, transform, material) {
            Ok(_handle) => {
                allocated_count += 1;
            }
            Err(e) => {
                log::warn!("Failed to allocate billboard ({}), stopping trail rendering", e);
                break;
            }
        }
    }
    
    log::trace!("Allocated {} billboards from pool for rendering", allocated_count);
    
    Ok(())
}
